### ISSUE TITLE
Broken example

### ISSUE THREAD

**Issue by 8secz-johndpope** [eroscai/SZAVPlayer#13]
<img width="903" alt="Screen Shot 2021-08-15 at 12 47 12 am" src="https://user-images.githubusercontent.com/50567111/129450214-c5b8b871-e55f-4b4b-9865-d170c4a302bc.png">
<img width="2381" alt="Screen Shot 2021-08-15 at 12 49 38 am" src="https://user-images.githubusercontent.com/50567111/129450217-bdb41cca-e189-4eb8-b289-e0f7f342e616.png">

**Comment by eroscai** [comment]
The Example project should work normally without new pod install. I just used a new clone project to test and it is normal.
- What version of XCode are you using?
- You can try to clone the new Project again, and then directly open `.xcworkspace` file to run.

**Comment by 8secz-johndpope** [comment]
when I deleted those lines - it worked fine. I'm on xcode 12.5.1

**Comment by 8secz-johndpope** [comment]
From error - Podfile probably needs rebuilding.
