### ISSUE TITLE
Delete single cache item by unique ID

### ISSUE THREAD

**Issue by binho** [eroscai/SZAVPlayer#14]
Would be possible to add support for deleting a single cache item by unique ID?

in SZAVPlayerCache add something like:
```swift
public func delete(uniqueID: String) {
    let fileInfos = SZAVPlayerDatabase.shared.localFileInfos(uniqueID: uniqueID)
    guard fileInfos.count > 0 else { return }

    SZAVPlayerDatabase.shared.deleteMIMEType(uniqueID: uniqueID)

    for fileInfo in fileInfos {
        let fileURL = SZAVPlayerFileSystem.localFilePath(fileName: fileInfo.localFileName)
        SZAVPlayerFileSystem.delete(url: fileURL)
    }
    SZAVPlayerDatabase.shared.deleteLocalFileInfo(uniqueID: uniqueID)
}
```

**Comment by eroscai** [comment]
Why not? You can make a pull request, then i will merge it in.

**Comment by binho** [comment]
I've tried to make a PR and it was denied 🤔 
I'll check and try again. Thanks 👍

**Comment by eroscai** [comment]
You need fork the project first, then modify and push in your forked project, and then you can make a PR in your project.
The PR will be displayed in main project.

**Comment by binho** [comment]
Adding PR here for future ref: https://github.com/eroscai/SZAVPlayer/pull/15
