### ISSUE TITLE
AMR Audio load failed

### ISSUE THREAD

**Issue by nikeshakya** [eroscai/SZAVPlayer#16]
Hello, 
I am using this library to load media files from server urls but its failing to load AMR audio files with error The operation could not be completed. 
Please help!

**Comment by eroscai** [comment]
May be this format not supported by `AVPlayer`. `AVURLAsset` has a function to return all supported types [audiovisualTypes](https://developer.apple.com/documentation/avfoundation/avurlasset/1386800-audiovisualtypes).
You can check it out and below is searched from web:

- public.mpeg
- public.mpeg-2-video
- public.avi
- public.aifc-audio
- public.aac-audio
- public.mpeg-4
- public.au-audio
- public.aiff-audio
- public.mp2
- public.3gpp2
- public.ac3-audio
- public.mp3
- public.mpeg-2-transport-stream
- public.3gpp
- public.mpeg-4-audio

**Comment by nikeshakya** [comment]
@eroscai thanks for the reply. There is amr file time listed in AVFileType 
[
![Screen Shot 2021-09-09 at 12 09 47](https://user-images.githubusercontent.com/16401569/132634038-b9518225-9653-4aaa-adb2-da01ea206605.png)
](url)

Any workaround for this ? 
Thanks

**Comment by eroscai** [comment]
I think that is just a type definition. If you want whether it is supported by `AVPlayer`, you need check the function `audiovisualTypes`. 
I just checked and the result are similar to what i listed above.
