### ISSUE TITLE
url的请求多数失败

### ISSUE THREAD

**Issue by jonathanlu98** [eroscai/SZAVPlayer#2]
‼️ Error | 2020-02-25 14:14:24:393 file:SZAVPlayer.swift func:assetLoader(_:downloadingFailed:) line:579 msg:<<<<< Error Domain=NSURLErrorDomain Code=-999 "cancelled"

虽然有时能好，但是连接能力远不及原生avplayer

**Comment by eroscai** [comment]
是在模拟器还是真机上？
- 如果是真机上出现的话可以把经常失败的链接发出来看一下
- 如果是模拟器的话需要全退一下模拟器再重新测试，这个是模拟器的BUG

**Comment by jonathanlu98** [comment]
你好，大概是模拟器的Bug
感谢解决问题 ^-^
