### ISSUE TITLE
Will this support Play and Cache simultaneously ?

### ISSUE THREAD

**Issue by maheshm504** [eroscai/SZAVPlayer#23]
We tried but its not working we are fetching videos from Dash Camera through Wifi connected

but its playing only after the file downloaded

Can you get me some solution ?

**Comment by eroscai** [comment]
I guess Dash Camera does not support range request, it is only available play and cache simultaneously with range request.
You can check this line, the variable `isByteRangeAccessSupported` is used to detect whether the range request supported.
https://github.com/eroscai/SZAVPlayer/blob/3c2280a0fc79f96b2771f71fcf7c97f8cbb39d75/Sources/Classes/SZAVPlayerAssetLoader.swift#L151-L154
