### ISSUE TITLE
Simulator compatibility

### ISSUE THREAD

**Issue by sushant-is-here** [eroscai/SZAVPlayer#24]
I know you have said that there are bugs/incompatibilities with the simulator. Its very annoying not being able to use simulator - can you please share what you know about the issue? I wouldn't mind trying to have a go at trying to fix myself and contributing back to your project.

**Comment by eroscai** [comment]
Well, actually there really isn't much issue to share. Sometimes it is suddenly unable to play, and it returns directly to failure when it start playing, but it never happens in real device.
When this problem happens, you can only fix it by restart simulator.

**Comment by sushant40** [comment]
I see it every time on my simulator brave tried resetting them. Nothing seems to work. :(

My colleague is tuning a intel Mac. Works for her. Never works on my M1. Wonder if that's somehow related.

**Comment by eroscai** [comment]
I think it is easier to confirm whether it is the problem of the system itself. You can create new empty project and use AVPlayer directly to play local files, if it is still not working, i think you can only tested with real device. Then you can also post on the apple forum to see if anyone else has a solution.
