### ISSUE TITLE
支持后台播放

### ISSUE THREAD

**Issue by justinjcode** [eroscai/SZAVPlayer#25]
作者有计划支持后台播放吗？

**Comment by eroscai** [comment]
这个可以说是已经支持了，因为本身就是系统层面的功能，是直接调用系统提供的API来实现的。
不过库里面也提供了便捷使用的工具类方法，分别是active和deactive，位置在这里https://github.com/eroscai/SZAVPlayer/blob/3c2280a0fc79f96b2771f71fcf7c97f8cbb39d75/Sources/Classes/SZAVPlayer.swift#L523
另外参考一下需要后台播放时的相关设置：https://stackoverflow.com/a/29140493

**Comment by justinjcode** [comment]
感谢大佬回复。用demo试了一下，确实可以！
