### ISSUE TITLE
如何判断视频真正的在播放？

### ISSUE THREAD

**Issue by SPGbayonet** [eroscai/SZAVPlayer#26]
您好，在我的项目中，使用该框架播放视频中。**大概率复现卡在已加载第一帧，或有播放进度变化但没有真正的播放。**
第二次进入时又很正常播放。

无法播放时nslog
[connection] nw_resolver_start_query_timer_block_invoke [C52] Query fired: did not receive all answers in time for oss-cn-beijing.aliyuncs.com:443

SZAVPlayerStatus, 这个值似乎并不准确？我有什么办法能拿到真正的播放状态吗，这样如果播放不正常我可以走重新加载的逻辑。

并且播放不正常时，它阻止了其他响应事件的传递。

**Comment by eroscai** [comment]
你贴的log里显示的貌似是跟网络相关的错误吧？你可以按照如下几个项确认一下：
1. 设置进去的URL是不是外网可访问的？是不是有一些自定义请求header之类的需要传递？如果有自定义请求header需求可以使用`SZAVPlayerConfig`里的2个字段`headersForContentInfoRequest`和`headersForDataRequest`进行传递
2. 如果不是第一项，你可以使用这个URL在工程DEMO里尝试一下，如果发现不正常可以把这个URL贴上来，我尝试复现一下看看
3. 如果工程DEMO里正常，而在你自己的项目不正常，那你可以弄个能复现问题的简单DEMO给我，我空了可以帮你看看
4. 同时也可以确认一下设置视频视图frame的时机的大小是否正确，比如是否可能视频已经开始播放了视图大小还是为0这种，如果有这种可能性可以先尝试使用固定容器大小测试看看

**Comment by SPGbayonet** [comment]
谢谢。已经排查到了。是header和 阿里云oss报错的问题。会导致这些问题
