### ISSUE TITLE
播时长较长的视频发生memory issue

### ISSUE THREAD

**Issue by justinjcode** [eroscai/SZAVPlayer#27]
![image](https://user-images.githubusercontent.com/15227472/175923139-4ac28aeb-79cd-4218-80ca-39284a357391.png)
![image](https://user-images.githubusercontent.com/15227472/175923308-43ff4bff-e625-44e2-8f18-bba0f5b1cfa6.png)
播1小时以上的视频，内存很快就涨起来了
另外player销毁后，下载任务没有销毁，内存还是持续上涨。

**Comment by eroscai** [comment]
好的，当我有空闲时间时会跟进一下，不过你可以提供一些更详细一点的信息：
1. 播放1小时视频时的内存问题是常规使用场景下就出现还是需要一些特殊条件？比如在工程DEMO里面设置长视频时是否同样出现？
2. player销毁问题也是同上，是否可以在工程DEMO里复现？

> 如果工程DEMO里能复现，能提供一个外网能访问的长视频链接最好了。

**Comment by eroscai** [comment]
问题2已经修复，cancel的时候没有调用markAsFinished方法确实是个问题，之前在其他场景中有修复过，但是忘记同步到这个库里了。
至于问题1里的`dataLoader.cancel()`方法调用`cancelAllOperations`方法来取消现有的全部operation的逻辑，我大概回忆了一下这样写的原因：
- resourceLoader(_ : didCancel loadingRequest: )方法调用的时机我记得一般有两种情况
    - 一种是用户触发了seekToTime方法，也就是产生了新的Range请求
    - 一种是在不同iOS系统版本下dataRequest的触发逻辑会有不同表现，简单来说data请求开始时会有未预期的cancel回调，接着发来一个新的data请求
- 不管是针对上述两种情况还是其他cancel调用的情况，应该都可以理解为把现有请求取消掉，为即将触发的新的请求腾出网络资源应该是还算合理的做法
    - 如果不做清理操作可能出现的一种情况是seekToTime等方法调用时会等待比较长的时间（之前其他的data请求占着网络资源）

你可以使用最新的master分支代码来测试你的问题是否正常，如果OK的话到时候我发布一个小版本上去

**Comment by justinjcode** [comment]
感谢及时的回复和跟进，按你描述的逻辑应该是没问题的。
由于我项目中有些定制化的需求，所以我切了个新分支加了些接口，现在不大方便切回去验证，实在不好意思😂



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: eroscai ***@***.***&gt;
发送时间: 2022年7月2日 11:20
收件人: eroscai/SZAVPlayer ***@***.***&gt;
抄送: justin ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [eroscai/SZAVPlayer] 播时长较长的视频发生memory issue (Issue #27)





 
问题2已经修复，cancel的时候没有调用markAsFinished方法确实是个问题，之前在其他场景中有修复过，但是忘记同步到这个库里了。
 至于问题1里的dataLoader.cancel()方法调用cancelAllOperations方法来取消现有的全部operation的逻辑，我大概回忆了一下这样写的原因：
  
resourceLoader(_ : didCancel loadingRequest: )方法调用的时机我记得一般有两种情况  
一种是用户触发了seekToTime方法，也就是产生了新的Range请求 

一种是在不同iOS系统版本下dataRequest的触发逻辑会有不同表现，简单来说data请求开始时会有未预期的cancel回调，接着发来一个新的data请求 
 

不管是针对上述两种情况还是其他cancel调用的情况，应该都可以理解为把现有请求取消掉，为即将触发的新的请求腾出网络资源应该是还算合理的做法  
如果不做清理操作可能出现的一种情况是seekToTime等方法调用时会等待比较长的时间（之前其他的data请求占着网络资源） 
 
 
你可以使用最新的master分支代码来测试你的问题是否正常，如果OK的话到时候我发布一个小版本上去
