### ISSUE TITLE
在测试中发现Flac格式的音乐进度存在问题

### ISSUE THREAD

**Issue by jonathanlu98** [eroscai/SZAVPlayer#3]
作者，你好 
感谢你推出的优秀的框架供大家学习
在测试中，我发现从网络下载播放Flac格式的音乐在拖动进度条后，继续播放的时间会有偏差，而mp3不会是这样的问题 。

**Comment by eroscai** [comment]
可以提供几个你发现问题的flac的音频地址么？我周末有空的时候看看能否解决

**Comment by jonathanlu98** [comment]
https://jlsptfy-music.oss-cn-shanghai.aliyuncs.com/4b9b_b0a3_def0_41921c99a729d212a0a345a47f669e1a.flac

**Comment by jonathanlu98** [comment]
他的码率为998273

**Comment by eroscai** [comment]
查阅了一下资料发现flac的编码是VBR编码，这里有[VBR的WIKI](https://en.wikipedia.org/wiki/Variable_bitrate)里面写着
> Additionally, variable rate encoding is inherent in lossless compression schemes such as FLAC and Apple Lossless.

而AVFoundation使用seek方法时使用AverageBitRate方式计算。
```
averageBitRate = totalBytes / duration
offset = seekTime * averageBitRate
```

所以会有偏差，貌似无解。

**Comment by jonathanlu98** [comment]
的确  调用AVFoundation的也是   那只能控制mp3格式了 感谢作者解答
