### ISSUE TITLE
remoteCommand的问题

### ISSUE THREAD

**Issue by jonathanlu98** [eroscai/SZAVPlayer#4]
在setupRemoteTransportControls方法中，previousTrackCommand.addTarget中  handleRemoteCommand(remoteCommand: .next)的错误

**Comment by eroscai** [comment]
感谢反馈，已修复并发布了新版本1.1.4

**Comment by jonathanlu98** [comment]
还有一个问题  就是当app进入后台时，remoteCommand不会响应操作
因为我把delegate写在某个viewController中
作者是否能够解决在后台使用remoteCommand   我目前解决的是在Appdelegate进行beginReceivingRemoteControlEvents

**Comment by eroscai** [comment]
app在后台持续进行音频播放需要设置2个地方：
- `AVAudioSession` 激活和设置，可以使用 `SZAVPlayer` 的 `activeAudioSession()` 方法
- Info.plist里面添加 `UIBackgroundModes`

**Comment by jonathanlu98** [comment]
已解决
感谢指导
