### ISSUE TITLE
缓冲问题

### ISSUE THREAD

**Issue by chaocharleswang** [eroscai/SZAVPlayer#5]
测试了一些较长的网络视频（mp4格式，约1小时）

seek后经常存在以下两种错误情况:
1. 视频画面不动，有声音，时间进度在走
2. 视频画面不动，没有声音，时间进度在走

**Comment by eroscai** [comment]
方便的话把能复现问题的视频地址发一下，我空了看看能否复现

**Comment by chaocharleswang** [comment]
1. 我用的是YouTube视频，比如下面这个1小时视频
https://www.youtube.com/watch?v=TKmGU77INaM
可以通过https://savieo.com/得到视频地址

2. 我用的是iPhone X

**Comment by eroscai** [comment]
周末测了测发现不一定是长视频才出现，我选取了一些油管的短视频也会出现这个问题。
然后我试了下完全走AVPlayer自己的加载模式是正常的，如果急用的话可以修改 `SZAVPlayerConfig` 的 `isLocalURL` 为 `true`。这样改的话视频数据加载会走系统自己处理的方式，能正常seek这类视频的进度，但是会失去缓存的过程。

不急的话可以等我尝试把问题修复好，初步排查发现是视频连接速度不太好时会有很多细碎的Range数据同时请求过来，之前库里实现是一次只处理一个数据请求，可能需要修改成同时处理多个数据请求再看看会不会正常，这个需要一定的时间。

**Comment by chaocharleswang** [comment]
谢谢回复！不急用，我现在用的是SGPlayer。偶然间发现SZAVPlayer，对其中AVAssetResourceLoader的运用很感兴趣，测试后发现很适合我的项目需求，期待进一步改进，会继续支持！

**Comment by eroscai** [comment]
刚更新了1.3.0版本，重构了加载方式，你可以试一下是否修复到了你的问题，我自测是可以的。
