### ISSUE TITLE
full screen mode ?

### ISSUE THREAD

**Issue by M0TRIX** [eroscai/SZAVPlayer#6]
I was wondering if you could add full-screen mode in your library ?

**Comment by eroscai** [comment]
The full screen mode is actually a function strongly related to the UI. Usually, displaying a video in full screen requires a lot of interaction with the `SuperView` and `ViewController` of `AVPlayer`, so it is difficult to provide a general full screen function in the `SZAVPlayer` library.

It is not too difficult if you want to implement it yourself, the steps are as follows:
1. Automatically or Manually trigger the full-screen landscape mode. ([Force landscape mode in one ViewController using Swift](https://stackoverflow.com/a/40859280/2805450))
2. At this time, the `Frame` of the `ViewController` has been changed, and it can be re-adapted to the width and height of the currently displayed views (if you using automatic layout, theoretically no need to modify).
3. Don't forget to re-adapt the view's width and height when changing from landscape mode back to portrait mode.
