### ISSUE TITLE
Trouble figuring out caching mechanism.

### ISSUE THREAD

**Issue by joeslopy** [eroscai/SZAVPlayer#7]
Hey just wanna say absolutely awesome pod! The fact that you did this all alone is super impressive! I'm building a story feature where a user will launch a Viewcontroller (StoryVC) when clicking on their profile picture from ProfileVC. In this new viewcontroller is where i initialize the cache and utilize your pod. When I go back and forth between videos in the StoryVC the video does not re-download. When I dismiss and relaunch the StoryVC it does re-download and shows up in network usage. Is this because I'm going back and forth between VCs? I'd greatly appreciate it if you could let me know a work around to this or if this is a bug/feature. It seams that the function save from SZAvPlayerCache NSObject is never called so I'm not sure if the file is actually being saved to the local device? Anyways, thanks again for this awesome pod and please get back to me if you have the time. Thanks!

**Comment by eroscai** [comment]
I am very glad that this library can help you a bit.
Let me help you sort out the loading process. From the Main Flow chart of README, you can see that setupPlayer will generally have two stages during the loading:
1. InfoRequest request. At this stage, information such as `contentType`, `contentLength`, `isByteRangeAccessSupported`, etc. will be obtained for filling. You can refer to the `handleContentInfoRequest` method of `SZAVPlayerAssetLoader`.
2. After the previous request is filled successfully, the system will initiate 1~N DataRequests. Exactly speaking, it will initiate a DataRequest with a `Range` request header. This stage will be managed by `SZAVPlayerDataLoader`, where `SZAVPlayerDataLoaderOperation` will check whether there is any loaded content locally based on the `Range`, and then maximize the use of local data to splice a series of `LocalFileRequest` and `RemoteRequest`. `LocalFileRequest` reads data directly from local files, `RemoteRequest` uses `SZAVPlayerRequestOperation` to initiate `URLSessionDataTask` for real-time download, and if the download is successful, it will be stored locally with `Range`. This process can refer to the 96 line `work(completion: @escaping CompletionHandler)` method of `SZAVPlayerDataLoaderOperation`.

If the `RemoteRequest` of step 2 ends normally, it will call back to the `requestOperation(_ operation: SZAVPlayerRequestOperation, didCompleteWithError error: Error?)` delegate on line 219 of `SZAVPlayerDataLoaderOperation`. Lines 221 to 224 are the codes store data locally:

```swift
if shouldSaveData, let mediaData = mediaData, mediaData.count > 0 {
    SZAVPlayerCache.shared.save(uniqueID: uniqueID, mediaData: mediaData, startOffset: operation.startOffset)
    self.mediaData = nil
}
```

If you find that it is reloaded every time you re-enter VC, you can try to break at this point to see which conditions are not met. Possible exceptions are:
1. An error occurred during the request.
2. `uniqueID` is inconsistent every time. If `uniqueID` is not explicitly set, it will automatically generate one based on the incoming `url`, so if the `url` set each time is inconsistent, it will cause the `cache` to not be used normally.
3. Other points that I did not expect, if you can reproduce stably here, you can get a reproducible DEMO for me to debug.

If you have any questions about other please don't hesitate to contact me again.

**Comment by joeslopy** [comment]
Thank you so much! This was so insightful, I will try to check out the uniqueID thing and if point #3 is the case I will definitely get back to you on it to hopefully help you improve your repo! Just wanna say again thank you! Tt's very kind of you to take time out of your day to not only create this repo, but to also answer questions!

**Comment by joeslopy** [comment]
Ok, so I checked whats going on. 

1. Unique ID is consistent so thats not an issue
2. Dataloader is being called
3. func dataLoader(_ loader: SZAVPlayerDataLoader, didReceive data: Data, dataRequest: SZAVPlayerDataRequest) is being called
4. dataLoader(_ loader: SZAVPlayerDataLoader, didFinishRequest dataRequest: SZAVPlayerDataRequest, error: Error?) is not being called and neither is  
requestOperation(_ operation: SZAVPlayerRequestOperation, didCompleteWithError error: Error?) 

Not sure whats going wrong here? Please let me know what you think might be the issue if you have the time. If you need extra details let me know also. Thanks!

**Comment by eroscai** [comment]
The didReceive delegate calls indicate that the data is being continuously loaded. The didFinishRequest delegate has not been called, confirm whether the request has really ended. For example, is it loading a very large video and it is still in the process of loading?
1. You can try to set the link you requested to the current DEMO project to see if it is normal. If it is abnormal, you can send the link to me to reproduce problem.
2. If the DEMO project is normal, try to write a NEW simple DEMO project that can reproduce the problem by yourself, and then send it to me
3. If you find that the problem is normal after rewriting a DEMO project, you can compare the logic of the newly written DEMO and the actual project. This situation can only be judged by yourself.

**Comment by joeslopy** [comment]
Thanks,

The caching is working just fine in the demo ill try to compare what the problem is in my source project. Thanks again!
