### ISSUE TITLE
Player plays from remote after video is cached

### ISSUE THREAD

**Issue by alexeyndru** [eroscai/SZAVPlayer#8]
Situation: player managed to download and cache the video. When I play again the video, it appears to load it from remote url and not from the cache. If I disable internet connection, the video is played from cache flawlessly.

What should I change so a cached video is always played and not the remote one?

Thanks

**Comment by eroscai** [comment]
May be the current video does not fully cached, and the remote request currently being loaded is belong to another range. Which range request is triggered is completely controlled by Apple.
You can add breakpoint to the `addRemoteRequest` function in the `SZAVPlayerDataLoaderOperation` class to view the current range that needs to be requested.

**Comment by alexeyndru** [comment]
Thank you for your response. My videos are short and they get completely downloaded. Also it doesn't enter addRemoteRequest function. Instead, it goes through the cache. Still, when I look at network activity, I see data fetched from server as soon as I start to play the video, and I see how the video is stalling for a little bit as though it is fetching data from server. But if I stop the internet, videos will play instantly and from cache. Any other clues?

I forgot to tell you that the library is amazing otherwise. Thank you for the effort, as it is not trivial at all.

**Comment by eroscai** [comment]
If it doesn't enter addRemoteRequest function, there is no way to trigger network activity. You can set your short video url to DEMO project to test if it is normal, if not, please send these links to me, i will check it when have time

**Comment by eroscai** [comment]
You can check whether the ContentInfo has been marked as expired, you can add a break point to this line.
https://github.com/eroscai/SZAVPlayer/blob/786b5337cae31ba1225514329b3d4b96d49bbc2e/Sources/Classes/SZAVPlayerAssetLoader.swift#L87

Currently if the interval between two requests exceeds 1 hour, it will be marked as expired, and then new ContentInfo will be requested. 
If the request is successful, the ContentInfo will be updated to the latest. 
If it failes for some reason, it will still try to use the locally existing ContentInfo, regardless of whether is is marked as expired.
https://github.com/eroscai/SZAVPlayer/blob/786b5337cae31ba1225514329b3d4b96d49bbc2e/Sources/Classes/SZAVPlayerAssetLoader.swift#L136

If this is not the cause of the problem, you can set your short video url to the DEMO project to test whether it is normal. If it is not, please send me these links, and i will test it when i'm free.

**Comment by alexeyndru** [comment]
I tested the Demo with my videos and they appear to work correctly. What i am trying to achieve in my app is preloading the videos. So I have multiple players which i setup initially with videos URLs. You know how in TikTok when user scrolls the next video plays instantly. Like in tik tok, my players play each at a time, but I make them download in advance the videos. In your demo you switch videos on the same player. After playing them all. when I replay they play from disk, not server. I am unable to achieve this so far. Will keep trying.

**Comment by alexeyndru** [comment]
Managed to solve my problem. The library works perfectly, it was something else. I was making a snapshot of the first frame of video and that was from remote url. Thanks again!
