### ISSUE TITLE
Adding custom http request header?

### ISSUE THREAD

**Issue by ggua5470** [eroscai/SZAVPlayer#9]
Is it possible to add http request header? E.g. adding a header for "Referer".
Sometimes we need to check the referer to limit hot links, from our server, or by the CDN providers.

There are two places adding a custom header field:
https://github.com/eroscai/SZAVPlayer/search?q=forHTTPHeaderField

Thanks

**Comment by eroscai** [comment]
Yes, this can be added, I will add it when I have time on the weekend.

**Comment by ggua5470** [comment]
Great!

**Comment by eroscai** [comment]
I released a new version `1.3.1`. 
You can add custom headers to ContentInfo and Data Requests, like this
https://github.com/eroscai/SZAVPlayer/blob/bac3d4dbf009fe9166bf67c24f17638b4a2f748b/Example/SZAVPlayer/VideoView/VideoViewController.swift#L239-L248

**Comment by ggua5470** [comment]
Thanks very much.
Already using it ^_^
